user_homepage:
    path:     /
    defaults: { _controller: userBundle:Default:index }
user_index:
    path:     /user/index
    defaults: { _controller: userBundle:User:index }
user_add:
    path:     /user/add
    defaults: { _controller: userBundle:User:add }
user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: userBundle:User:edit }
user_view:
    path:     /user/view/{id}
    defaults: { _controller: userBundle:User:view }
user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: userBundle:User:delete }